### ISSUE TITLE
Not working correctly for IPV6

### ISSUE THREAD

**Issue by ankushs92** [ankushs92/Java-DB-IP#12]
The code works correctly for IPV4's but not for IPV6 addresses.

**Comment by ptheohar** [comment]
Hi @ankushs92 , are you going to fix this?
Currently we use the online API for the IPV6 addresses.

**Comment by ankushs92** [comment]
I am a bit busy at the moment, so unfortunately I won't be able to do it any time soon. However, I can give you a few pointers on how to proceed with it and maybe you can submit a pull request?
It would be great if you could :D

**Comment by ankushs92** [comment]
I might work on it this week. Can't guarantee it though

**Comment by ptheohar** [comment]
Thanks, I will check also when I have some time.

**Comment by ankushs92** [comment]
Done. Will update the mvn links by today.
