### ISSUE TITLE
Reducing heap usage

### ISSUE THREAD

**Issue by jatins** [ankushs92/Java-DB-IP#14]
> The entire dataset is loaded into a TreeMap . Make sure that you have about **3 GB of Heap space** available to load it.

3GB might be too much for some apps. Heap usage can be brought down by interning city/province strings in `ResourceImporter`. I was able to get down heap usage from 2.4G to 1.7G by interning strings. 

Further, by using integer instead of `InetAddress` in `GeoAttributes`, the heap usage further came down to 1.3G.  (Not that this won't affect the API, which will still accept `InetAddress`).

I think the gains are significant, and I'd be happy to create a pull request for the same. Let me know what you think!

**Comment by ankushs92** [comment]
Hello Jatin.

Thanks for the feedback. This project was made in quite a hurry. I had to
get rid of another system that was built on Redis and had only 3-4 days to
build this one. I must profess of having limited knowledge of 'interning
strings', but whole heartedly agree with your second one.
I agree on the point that the gains would indeed be significant. Feel free
to make a pull request, by all means!

Thank you.
Ankush.

**Comment by jatins** [comment]
Created pull request #15

**Comment by ankushs92** [comment]
Thanks , I'll update on maven soon enough.
